apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app-volume
        configMap:
          name: static-website-content

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: static-website-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>GCP + GKE Deployment</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; background: #f0f8ff; margin: 0; padding: 0; }
            .container { max-width: 800px; margin: 50px auto; padding: 20px; background: white; border-radius: 10px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
            h1 { color: #4285f4; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 Successfully Deployed on GKE!</h1>
            <p>This static website is running on Google Kubernetes Engine (GKE).</p>
            <p>Deployed using Terraform + GitHub Actions.</p>
        </div>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: static-website-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: static-website